name: ci

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hlf-version:
          - 2.2.0
          - 2.2.3
          - 2.3.0
          - 2.3.2
    steps:
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./images/fabric-peer/${{matrix.hlf-version}}/Dockerfile
          push: true
          tags: quay.io/kfsoftware/fabric-peer:amd64-${{matrix.hlf-version}}-$RELEASE_VERSION
